HIGHLY_VAR_GENES_PATH: ".../highly_variable_genes_raw.csv"
H5AD_FILES: ".../*.h5ad"

model:
  vocab_size: 1002      # 1000 HVGs + 1 CLS + 1 MSK
  embed_dim: 288
  hidden_size: 288
  num_hidden_layers: 12
  num_attention_heads: 12
  model_ckpt: '.../val_best_loss.pt' # CHANGE THIS TO THE PATH OF THE TRAINED MODEL
  name: 'mcBERT_1024'
